apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: go-helloserver
  description: |
    [The Go HelloServer example project](https://github.com/Kheops-org/go-apps/tree/master/helloserver) is a simple example go app
    - It goes brr
    - It goes Go
    - It doesn't rickroll
    - Let's Go
  links:
    - url: https://github.com/Kheops-org/go-apps/tree/master/helloserver
      title: Source Code
      icon: github
    - url: https://argocd-server-sreez.apps.oc-med.wk.nt.local/applications/sreez/go-helloserver?view=tree&resource=
      title: ArgoCD Deployment
      icon: cached
    - url: http://localhost:8090
      title: HyperDX Logs and Monitoring
      icon: monitor_heart
  tags:
    - go
    - hello-world
  annotations:
    argocd/app-name: go-helloserver
    grafana/dashboard-selector: go-helloserver
spec:
  type: service
  lifecycle: experimental
  owner: team-c
