name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
  workflow_dispatch:

defaults:
  run:
    working-directory: helloserver

jobs:

  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Generate Time-Based Tag
      id: generate-tag
      run: |
        TAG=$(date +"%Y%m%d-%H%M%S")
        echo "::set-output name=tag::$TAG"
          
    - name: Login to Docker Registry
      uses: docker/login-action@v2
      with:
        registry: registry.mycompany.com
        username: ${{ secrets.NATIONTECH_REGISTRY_USER }}
        password: ${{ secrets.NATIONTECH_REGISTRY_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: registry.nationtech.io/go-helloserver:${{ steps.generate-tag.outputs.tag }}

    - name: Update Helm Chart Values
      run: |
        sed -i "s/tag: .*/tag: ${{ steps.generate-tag.outputs.tag }}/" ./helm/go-helloserver/values.yaml
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add ./helm/go-helloserver/values.yaml
        git commit -m "Upgraded go-helloserver deployment to ${{ steps.generate-tag.outputs.tag }}"
        git push
